### ISSUE TITLE
List all violations

### ISSUE THREAD

**Issue by sobolevn** [duo-labs/dlint#13]
Hi! Awesome project. It has a lot of strict checks and unique rules.

I am considering adding `Dlint` into `wemake-python-styleguide`,
but violations are not listed anywhere. So, you have to look through the source code to know what happened and how to fix it.

I would appreciate a complete list of violations with the solutions!

**Comment by mschwager** [comment]
Hi @sobolevn,

I'm closing this in favor of tracking it in #8. I'll be unavailable for a week or so, but this will be one of the first things I take care of when I'm back. Thanks for opening this, it helps me track priority!

**Comment by sobolevn** [comment]
Thanks! I will check it out and consider adding this tool to our `0.13` release.
