### ISSUE TITLE
DUO104 is used by eval and format string checks

### ISSUE THREAD

**Issue by minusworld** [duo-labs/dlint#15]
It looks like DUO104 is used both for eval and format strings and I am not sure if this is intentional.

https://github.com/duo-labs/dlint/blob/master/dlint/linters/bad_eval_use.py#L20
https://github.com/duo-labs/dlint/blob/master/dlint/linters/format_string.py#L24

**Comment by mschwager** [comment]
Good catch! The format string check was an experiment of mine - I'll remove it until something more concrete is created (if at all).
