### ISSUE TITLE
How are duo-labs/dlint and dlint-py/dlint related today?

### ISSUE THREAD

**Issue by hartwork** [duo-labs/dlint#48]
Hi!

I understand that Duo Labs are the original authors of Dlint. PyPI links to https://github.com/dlint-py/dlint but Google sends me to https://github.com/duo-labs/dlint and the two repos seem to be kept in sync some non-automated way?

It would be great to have a super visible note somewhere to answer that question. Did I overlook any less visible notes somewhere?

Thanks and best, Sebastian

**Comment by jordan-wright** [comment]
Hi there!

Sorry for the delay in getting back to you!

So this repository is the official Dlint repository from which PyPI releases are created. The repository at dlint-py/dlint is a community fork. There are active changes done on the fork and, at a regular interval, we import those changes back into the main repository.

There are also some community tools in that GH organization you might find useful such as a [GitHub Action for Dlint](https://github.com/dlint-py/dlint-action)

So the long story short is that you are always welcome to submit issues and pull requests to this repository, and if you use the code from PyPI, you're using the code from this repository.

**Comment by hartwork** [comment]
> So this repository is the official Dlint repository from which PyPI releases are created. The repository at dlint-py/dlint is a community fork. There are active changes done on the fork and, at a regular interval, we import those changes back into the main repository.
> 
> There are also some community tools in that GH organization you might find useful such as a [GitHub Action for Dlint](https://github.com/dlint-py/dlint-action)
> 
> So the long story short is that you are always welcome to submit issues and pull requests to this repository, [..]

To be fair, I don't feel like I have learned much from that explanation, especially not about rationale for those decisions.


> and if you use the code from PyPI, you're using the code from this repository.

It seems like the other way around to me: If I'm looking at PyPI and the two Git repos right now, what I see is:
- PyPI is at 0.10.3
- The commits and Git tag for 0.10.3 are in [the community repo](https://github.com/dlint-py/dlint/commits/master) but *not* the [duo labs one](https://github.com/duo-labs/dlint/commits/master)
- PyPI points to the [community repo](https://github.com/dlint-py/dlint/) for a project homepage.
