### ISSUE TITLE
Add linter for insecure cryptography use

### ISSUE THREAD

**Issue by mschwager** [duo-labs/dlint#6]
The Python [cryptography](https://cryptography.io/en/latest/) library has become the defacto standard for crytographic operations. We should detect known-insecure crytographic operations, e.g.

- `cryptography.hazmat.primitives.hashes.MD5`
- `cryptography.hazmat.primitives.hashes.SHA1`
- `cryptography.hazmat.primitives.ciphers.modes.ECB`

We should also investigate if there are any other pieces of functionality in the library worth detecting.

**Comment by alex** [comment]
PKCS1v15 when used with encryption is probably worthy of detection.
